### ISSUE TITLE
Java NullPointerException while using XML transform

### ISSUE THREAD

**Issue by hancehans** [jcustenborder/kafka-connect-transform-xml#39]
Hi, we are trying to use Kafka connect xml transform to convert xml (https://www.confluent.io/hub/jcustenborder/kafka-connect-transform-xml), so that the xml message can be parsed as avro in confluent.
We use Confluent 5.5.0, java jdk1.8.0_252
We try from a simple xml file, however we encountered an error with this error stack:
[2021-02-05 15:05:24,715] ERROR Failed to start task XML_TEST_TRANSFORM-0 (org.apache.kafka.connect.runtime.Worker)
org.apache.kafka.connect.errors.ConnectException: java.lang.NullPointerException
        at org.apache.kafka.connect.runtime.ConnectorConfig.transformations(ConnectorConfig.java:264)
        at org.apache.kafka.connect.runtime.Worker.buildWorkerTask(Worker.java:520)
        at org.apache.kafka.connect.runtime.Worker.startTask(Worker.java:472)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder.startTask(DistributedHerder.java:1147)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder.access$1600(DistributedHerder.java:126)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder$12.call(DistributedHerder.java:1162)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder$12.call(DistributedHerder.java:1158)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
        at com.github.jcustenborder.kafka.connect.transform.xml.XSDCompiler.compileContext(XSDCompiler.java:146)
        at com.github.jcustenborder.kafka.connect.transform.xml.FromXml.configure(FromXml.java:130)
        at org.apache.kafka.connect.runtime.ConnectorConfig.transformations(ConnectorConfig.java:261)
        ... 10 more

No additional trace available in the log (root logger alrady set to TRACE),
I wonder what causes the error, any idea regarding this error/ get more verbosity of the error appreciated
![Config](https://user-images.githubusercontent.com/28133327/107312087-3b898500-6ac2-11eb-81df-6752e764fc32.JPG)
![xmlfile](https://user-images.githubusercontent.com/28133327/107312091-3d534880-6ac2-11eb-85b8-4a91e156a785.JPG)
![xsdschema](https://user-images.githubusercontent.com/28133327/107312092-3debdf00-6ac2-11eb-897b-8a1b4ff6d9c0.JPG)

**Comment by fayezosaadi** [comment]
Hi, I also ran into the same exact issue, downgrading the java version solved the the problem for me.

**Comment by jpnorenam** [comment]
@fayezosaadi Hi, which version made it work?
