### ISSUE TITLE
NullPointerException when java compiler is not installed

### ISSUE THREAD

**Issue by 1123** [jcustenborder/kafka-connect-transform-xml#44]
Great Project :-) 

When running in an environment where javac is not installed, a NullPointer Exception is thrown on the following line: 
https://github.com/jcustenborder/kafka-connect-transform-xml/blob/30e3376ccfae7340b4e588b2827fc2a918146351/src/main/java/com/github/jcustenborder/kafka/connect/transform/xml/XSDCompiler.java#L146

It would be great to throw a more meaningful exception such as (java compiler is not installed, therefore we cannot translate the schema to Java classes).

**Comment by jpnorenam** [comment]
Hi @1123, the error you faced looks something like this?
```
ERROR Failed to start task sjms2-source-connector0 (org.apache.kafka.connect.runtime.Worker) [StartAndStopExecutor-connect-1-2]
org.apache.kafka.connect.errors.ConnectException: java.lang.NullPointerException
	at org.apache.kafka.connect.runtime.ConnectorConfig.transformations(ConnectorConfig.java:296)
	at org.apache.kafka.connect.runtime.Worker.buildWorkerTask(Worker.java:605)
	at org.apache.kafka.connect.runtime.Worker.startTask(Worker.java:555)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.startTask(DistributedHerder.java:1251)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.access$1700(DistributedHerder.java:127)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder$10.call(DistributedHerder.java:1266)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder$10.call(DistributedHerder.java:1262)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.NullPointerException
	at com.github.jcustenborder.kafka.connect.transform.xml.XSDCompiler.compileContext(XSDCompiler.java:86)
	at com.github.jcustenborder.kafka.connect.transform.xml.FromXml.configure(FromXml.java:95)
	at org.apache.kafka.connect.runtime.ConnectorConfig.transformations(ConnectorConfig.java:285)
	... 10 more
```

I am using the following `Dockerfile`, but installing the javac doesn't solve errors.
```
FROM strimzi/kafka:0.20.0-kafka-2.6.0
USER root:root

RUN yum install unzip tree -y

RUN mkdir -p /opt/kafka/plugins/

# CAMEL SJMS2 KAFKA CONNECTOR
RUN curl -sL https://repo1.maven.org/maven2/org/apache/camel/kafkaconnector/camel-sjms2-kafka-connector/0.11.0/camel-sjms2-kafka-connector-0.11.0-package.tar.gz \
    -o /opt/kafka/plugins/camel/camel-sjms2-kafka-connector-0.11.0-package.tar.gz \
    && tar xzvf /opt/kafka/plugins/camel/camel-sjms2-kafka-connector-0.11.0-package.tar.gz \
    && rm /opt/kafka/plugins/camel/camel-sjms2-kafka-connector-0.11.0-package.tar.gz

######## XML TRANSFORMATION
RUN mkdir -p /opt/kafka/plugins/jcustenborder/
WORKDIR /opt/kafka/plugins/jcustenborder/

# https://github.com/jcustenborder/kafka-connect-transform-xml
RUN curl -sL https://repo1.maven.org/maven2/com/github/jcustenborder/kafka/connect/kafka-connect-transform-xml/0.1.0.4/kafka-connect-transform-xml-0.1.0.4.tar.gz \
    -o /opt/kafka/plugins/jcustenborder/kafka-connect-transform-xml-0.1.0.4.tar.gz \
    && tar xzvf /opt/kafka/plugins/jcustenborder/kafka-connect-transform-xml-0.1.0.4.tar.gz \
    && rm /opt/kafka/plugins/jcustenborder/kafka-connect-transform-xml-0.1.0.4.tar.gz

RUN yum install java-1.8.0-openjdk java-1.8.0-openjdk-devel -y

WORKDIR /opt/kafka/
USER 1001
```
